### ISSUE TITLE
-o (output) flag error

### ISSUE THREAD

**Issue by Electron7-7** [Electron7-7/shcript#2]
### Command:
shcript -z -o="/home/thelegend27" test2

### Output:
Traceback (most recent call last):
  File "shcript.py", line 64, in <module>
  File "shcript.py", line 13, in Main
  File "pathlib.py", line 1078, in write_text
  File "pathlib.py", line 1044, in open
IsADirectoryError: [Errno 21] Is a directory: '/home/thelegend27'
[48095] Failed to execute script 'shcript' due to unhandled exception!

**Comment by Electron7-7** [comment]
Fixed

**Comment by Electron7-7** [comment]
Issue was me being dumb and not adding the filename to the user-supplied filepath after checking if it was valid
